[project]
name = "eogtouch"
version = "0.1.0"
description = "A game to measure coordination of tactile systems and ocular systems"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastparquet>=2024.11.0",
    "pandas>=2.2.3",
    "pygame>=2.6.1",
]

[project.gui-scripts]
eogtouch = "eogtouch:main"

[tool.ruff]
preview = true
respect-gitignore = true
unsafe-fixes = false
line-length = 120
indent-width = 4
target-version = "py312"
exclude = [
    ".bzr", ".direnv", ".eggs", ".git", ".hg", ".mypy_cache", ".nox", ".pants.d",
    ".ruff_cache", ".svn", ".tox", ".venv", "__pypackages__", "_build",
    "buck-out", "build", "dist", "node_modules", "venv",
]
src = ["eogtouch"]

[tool.ruff.lint]
select = ["E", "F"]
extend-select = ["T201"]
ignore = ["E266"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[dependency-groups]
dev = [
    "ipython>=9.2.0",
    "python-lsp-server>=1.12.2",
    "ruff>=0.11.0",
]

[tool.setuptools]
packages = ["eogtouch"]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
